// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (x, a, b);
    input a, b;
    output x;

    C2 U0 (.Q(x), .A(a), .B(b));

    // signal values at the initial state:
    // !x !a !b
endmodule
