// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (x, a, c);
    input a, c;
    output x;

    C2 U0 (.Q(x), .A(a), .B(c));

    // signal values at the initial state:
    // !x !a !c
endmodule
