// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module UNTITLED (x, a, b, c);
    input a, b, c;
    output x;

    OR2 U1 (.O(U1_O), .A(c), .B(b));
    C2 U2 (.Q(x), .A(a), .B(U1_O));

    // signal values at the initial state:
    // !U1_O !x !a !b !c
endmodule
