// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module UNTITLED (ai, ro, ao, ri);
    input ao, ri;
    output ai, ro;

    AOI2BB2 U0 (.ON(ai), .A1N(ao), .A2N(U2_ON), .B1(ao), .B2(ri));
    AOI2BB2 U1 (.ON(ro), .A1N(ri), .A2N(U2_ON), .B1(ri), .B2(U2_ON));
    AOI2BB2 U2 (.ON(U2_ON), .A1N(ao), .A2N(U2_ON), .B1(ao), .B2(ai));

    // signal values at the initial state:
    // !ai !ro !U2_ON !ao !ri
endmodule
