// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (gn, gp, oc, uv, zc, gn_ack, gp_ack);
    input oc, uv, zc, gn_ack, gp_ack;
    output gn, gp;

    OR2 U1 (.O(U1_O), .A(zc), .B(uv));
    NOR2 U2 (.ON(gn), .A(gp_ack), .B(U1_O));
    NOR2 U4 (.ON(U4_ON), .A(gn_ack), .B(oc));
    C2 U5 (.Q(gp), .A(uv), .B(U4_ON));

    // signal values at the initial state:
    // !U1_O gn !U4_ON !gp !oc !uv !zc gn_ack !gp_ack
endmodule
