// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Test1 (req, ack);
    input req;
    output ack;

    assign ack = req;


    // signal values at the initial state:
    // !ack !req
endmodule
