// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (an, ap, oc, ri, ai, rn, rp);
    input an, ap, oc, ri;
    output ai, rn, rp;

    // This inverter should have a short delay
    INV _U0 (.ON(_U0_ON), .I(rp));
    AOI211 _U1 (.ON(_U1_ON), .A1(oc), .A2(_U0_ON), .B(rn), .C(ap));
    INV _U2 (.ON(_U2_ON), .I(_U1_ON));
    NOR2 _U3 (.ON(_U3_ON), .A(_U2_ON), .B(an));
    C2 _U4 (.Q(ai), .A(_U3_ON), .B(ri));
    // This inverter should have a short delay
    INV _U5 (.ON(_U5_ON), .I(oc));
    // This inverter should have a short delay
    INV _U6 (.ON(_U6_ON), .I(rn));
    OAI32 _U7 (.ON(_U7_ON), .A1(_U5_ON), .A2(ap), .A3(rp), .B1(_U6_ON), .B2(an));
    // This inverter should have a short delay
    INV _U8 (.ON(_U8_ON), .I(ri));
    AO21 _U9 (.O(rn), .A1(rn), .A2(_U8_ON), .B(_U7_ON));
    // This inverter should have a short delay
    INV _U10 (.ON(_U10_ON), .I(oc));
    NOR2 _U11 (.ON(_U11_ON), .A(rn), .B(oc));
    // This inverter should have a short delay
    INV _U12 (.ON(_U12_ON), .I(ri));
    // This inverter should have a short delay
    INV _U13 (.ON(_U13_ON), .I(oc));
    AOI32 _U14 (.ON(_U14_ON), .A1(_U12_ON), .A2(_U11_ON), .A3(ai), .B1(_U13_ON), .B2(ap));
    OAI21 _U15 (.ON(rp), .A1(_U10_ON), .A2(_U2_ON), .B(_U14_ON));

    // signal values at the initial state:
    // _U0_ON _U1_ON !_U2_ON _U3_ON !ai _U5_ON _U6_ON !_U7_ON _U8_ON !rn _U10_ON _U11_ON _U12_ON _U13_ON _U14_ON !rp !an !ap !oc !ri
endmodule
