// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module UNTITLED (r1, r2, r3, g1, g2, g3);

    input r1, r2, r3;
    output g1, g2, g3;

    C2 c1 (.Q(g1), .A(M1a_Q), .B(M3a_Q));
    C2 c2 (.Q(g2), .A(M1b_Q), .B(M2a_Q));
    C2 c3 (.Q(g3), .A(M3b_Q), .B(M2b_Q));

    AND2B M1a (.O(M1a_Q), .AN(M1b_Q), .B(r1));
    AND2B M1b (.O(M1b_Q), .AN(M1a_Q), .B(r2));

    AND2B M2a (.O(M2a_Q), .AN(M2b_Q), .B(r2));
    AND2B M2b (.O(M2b_Q), .AN(M2a_Q), .B(r3));

    AND2B M3a (.O(M3a_Q), .AN(M3b_Q), .B(r1));
    AND2B M3b (.O(M3b_Q), .AN(M3a_Q), .B(r3));

    // signal values at the initial state:
    // !g1 !g3 !g2 !M1b_Q !M1a_Q !M2a_Q !M2b_Q !M3b_Q !M3a_Q !r1 !r2 !r3
endmodule
