// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (ao, ri, uv, ai, ro, wuv);
    input ao, ri, uv;
    output ai, ro, wuv;

    AND2 _U0 (.O(ai), .A(_U9_O), .B(uv));
    NAND3B _U1 (.ON(_U1_ON), .AN(_U10_Q), .B(wuv), .C(uv));
    INV _U2 (.ON(ro), .I(_U1_ON));
    // This inverter should have a short delay
    INV _U3 (.ON(_U3_ON), .I(_U10_Q));
    AOI211 _U4 (.ON(_U4_ON), .A1(_U3_ON), .A2(wuv), .B(_U9_O), .C(ao));
    INV _U5 (.ON(wuv), .I(_U4_ON));
    // This inverter should have a short delay
    INV _U6 (.ON(_U6_ON), .I(ri));
    // This inverter should have a short delay
    INV _U7 (.ON(_U7_ON), .I(_U9_O));
    OAI32 _U8 (.ON(_U8_ON), .A1(_U6_ON), .A2(uv), .A3(_U10_Q), .B1(_U7_ON), .B2(ai));
    AO21 _U9 (.O(_U9_O), .A1(ri), .A2(ai), .B(_U8_ON));
    C2 _U10 (.Q(_U10_Q), .A(ao), .B(wuv));

    // signal values at the initial state:
    // !ai _U1_ON !ro _U3_ON _U4_ON !wuv _U6_ON _U7_ON !_U8_ON !_U9_O !_U10_Q !ao !ri !uv
endmodule
