// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (ad, ao, ri, ai, rd, ro);
    input ad, ao, ri;
    output ai, rd, ro;

    // This inverter should have a short delay
    INV _U0 (.ON(_U0_ON), .I(_U6_ON));
    AOI21 _U1 (.ON(ai), .A1(ri), .A2(_U4_QN), .B(_U0_ON));
    NOR2B _U2 (.ON(rd), .AN(ri), .B(_U6_ON));
    AND2 _U3 (.O(ro), .A(ri), .B(_U4_QN));
    NC2 _U4 (.QN(_U4_QN), .A(ao), .B(ri));
    AOI21 _U5 (.ON(_U5_ON), .A1(_U6_ON), .A2(ri), .B(ad));
    OAI21 _U6 (.ON(_U6_ON), .A1(ri), .A2(_U4_QN), .B(_U5_ON));

    // signal values at the initial state:
    // _U0_ON !ai !rd !ro _U4_QN _U5_ON !_U6_ON !ad !ao !ri
endmodule
