// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module Untitled (ao, ri, ai, ro);
    input ao, ri;
    output ai, ro;

    NOR2 _U0 (.ON(ai), .A(ao), .B(_U2_QN));
    AND2 _U1 (.O(ro), .A(ri), .B(_U2_QN));
    NC2 _U2 (.QN(_U2_QN), .A(ao), .B(ri));

    // signal values at the initial state:
    // !ai !ro _U2_QN !ao !ri
endmodule
