// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module concurrency (a0, a1, a2, a3, b);
    output a0, a1, a2, a3, b;

    INV _U0 (.ON(a0), .I(b));
    INV _U1 (.ON(a1), .I(b));
    INV _U2 (.ON(a2), .I(b));
    INV _U3 (.ON(a3), .I(b));
    AND4 _U4 (.O(_U4_O), .A(a0), .B(a1), .C(a2), .D(_U7_O));
    OA21 _U5 (.O(_U5_O), .A1(_U4_O), .A2(b), .B(a3));
    C2 _U6 (.Q(b), .A(_U5_O), .B(_U7_O));
    OR4 _U7 (.O(_U7_O), .A(_U4_O), .B(a0), .C(a1), .D(a2));

    // signal values at the initial state:
    // !a0 !a1 !a2 !a3 !_U4_O !_U5_O !b !_U7_O
endmodule
