// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module concurrency (b, a0, a1, a2, a3, a4, a5);
    output b, a0, a1, a2, a3, a4, a5;

    INV OUT_BUBBLE2 (.ON(OUT_BUBBLE2_ON), .I(U3_ON));
    NOR4B U3 (.ON(U3_ON), .AN(U13_QN), .B(a4), .C(a5), .D(a0));
    NC2 U4 (.QN(b), .A(U13_QN), .B(OUT_BUBBLE2_ON));
    INV U5 (.ON(a0), .I(b));
    INV U6 (.ON(a1), .I(b));
    INV U7 (.ON(a2), .I(b));
    INV U8 (.ON(a3), .I(b));
    INV U9 (.ON(a4), .I(b));
    INV U10 (.ON(a5), .I(b));
    NAND4 U12 (.ON(U12_ON), .A(OUT_BUBBLE18_ON), .B(a4), .C(a5), .D(a2));
    NC2 U13 (.QN(U13_QN), .A(OUT_BUBBLE18_ON), .B(U12_ON));
    INV OUT_BUBBLE15 (.ON(OUT_BUBBLE15_ON), .I(U16_ON));
    AOI221 U16 (.ON(U16_ON), .A1(a2), .A2(OUT_BUBBLE15_ON), .B1(a1), .B2(OUT_BUBBLE15_ON), .C(a3));
    INV OUT_BUBBLE18 (.ON(OUT_BUBBLE18_ON), .I(U19_ON));
    AOI32 U19 (.ON(U19_ON), .A1(a0), .A2(a1), .A3(OUT_BUBBLE15_ON), .B1(OUT_BUBBLE15_ON), .B2(OUT_BUBBLE18_ON));

    // signal values at the initial state:
    // !OUT_BUBBLE2_ON U3_ON !b !a0 !a1 !a2 !a3 !a4 !a5 U12_ON U13_QN !OUT_BUBBLE15_ON U16_ON !OUT_BUBBLE18_ON U19_ON
endmodule
