// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module concurrency (b, a0, a1, a2, a3);
    output b, a0, a1, a2, a3;

    AND4 U1 (.O(U1_O), .A(a3), .B(a1), .C(a2), .D(a0));
    OR4 U3 (.O(U3_O), .A(a3), .B(a1), .C(a2), .D(a0));
    C2 U4 (.Q(b), .A(U1_O), .B(U3_O));
    INV U5 (.ON(a0), .I(b));
    INV U6 (.ON(a1), .I(b));
    INV U7 (.ON(a2), .I(b));
    INV U8 (.ON(a3), .I(b));

    // signal values at the initial state:
    // !U1_O !U3_O !b !a0 !a1 !a2 !a3
endmodule
