// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module concurrency (a0, a1, a2, a3, a4, a5, b);
    output a0, a1, a2, a3, a4, a5, b;

    INV _U0 (.ON(a0), .I(b));
    INV _U1 (.ON(a1), .I(b));
    INV _U2 (.ON(a2), .I(b));
    INV _U3 (.ON(a3), .I(b));
    INV _U4 (.ON(a4), .I(b));
    INV _U5 (.ON(a5), .I(b));
    // This inverter should have a short delay
    INV _U6 (.ON(_U6_ON), .I(b));
    NOR3 _U7 (.ON(_U7_ON), .A(a2), .B(a3), .C(a4));
    // This inverter should have a short delay
    INV _U8 (.ON(_U8_ON), .I(_U14_Q));
    AOI31 _U9 (.ON(_U9_ON), .A1(a2), .A2(a3), .A3(a4), .B(_U8_ON));
    AOI22 _U10 (.ON(b), .A1(_U6_ON), .A2(_U14_Q), .B1(_U7_ON), .B2(_U9_ON));
    // This inverter should have a short delay
    INV _U11 (.ON(_U11_ON), .I(a5));
    AOI211 _U12 (.ON(_U12_ON), .A1(_U7_ON), .A2(a3), .B(_U11_ON), .C(_U9_ON));
    INV _U13 (.ON(_U13_ON), .I(_U12_ON));
    C2 _U14 (.Q(_U14_Q), .A(_U15_QN), .B(_U13_ON));
    NC2 _U15 (.QN(_U15_QN), .A(a0), .B(a1));

    // signal values at the initial state:
    // !a0 !a1 !a2 !a3 !a4 !a5 _U6_ON _U7_ON !_U8_ON _U9_ON !b _U11_ON !_U12_ON _U13_ON _U14_Q _U15_QN
endmodule
