// Verilog netlist generated by Workcraft 3 -- https://workcraft.org/
module concurrency (b, a0, a1, a2, a3, a4, a5, a6, a7);
    output b, a0, a1, a2, a3, a4, a5, a6, a7;

    INV OUT_BUBBLE2 (.ON(OUT_BUBBLE2_ON), .I(U3_ON));
    NOR4B U3 (.ON(U3_ON), .AN(U15_QN), .B(a2), .C(a7), .D(a1));
    NC2 U4 (.QN(b), .A(U15_QN), .B(OUT_BUBBLE2_ON));
    INV U5 (.ON(a0), .I(b));
    INV U6 (.ON(a1), .I(b));
    INV U7 (.ON(a2), .I(b));
    INV U8 (.ON(a3), .I(b));
    INV U9 (.ON(a4), .I(b));
    INV U10 (.ON(a5), .I(b));
    INV U11 (.ON(a6), .I(b));
    INV U12 (.ON(a7), .I(b));
    NAND4 U14 (.ON(U14_ON), .A(U20_QN), .B(a1), .C(a7), .D(a0));
    NC2 U15 (.QN(U15_QN), .A(U20_QN), .B(U14_ON));
    INV OUT_BUBBLE18 (.ON(OUT_BUBBLE18_ON), .I(U19_ON));
    NOR4B U19 (.ON(U19_ON), .AN(U23_QN), .B(a5), .C(a6), .D(a0));
    NC2 U20 (.QN(U20_QN), .A(U23_QN), .B(OUT_BUBBLE18_ON));
    NAND4 U22 (.ON(U22_ON), .A(U24_Q), .B(a5), .C(a6), .D(a2));
    NC2 U23 (.QN(U23_QN), .A(U24_Q), .B(U22_ON));
    C2 U24 (.Q(U24_Q), .A(a3), .B(a4));

    // signal values at the initial state:
    // !OUT_BUBBLE2_ON U3_ON !b !a0 !a1 !a2 !a3 !a4 !a5 !a6 !a7 U14_ON U15_QN !OUT_BUBBLE18_ON U19_ON !U20_QN U22_ON U23_QN !U24_Q
endmodule
